// src/constants/categoriesList.js

export const CATEGORIES = [
    "Accessories",
    "Art",
    "Automotive",
    "Animal",
    "Baby Items",
    "Bags",
    "Books",
    "Business Cards",
    "Clothing",
    "Cosmetics",
    "Documents",
    "Dish",
    "Electronics",
    "Eyewear",
    "Food Containers",
    "Footwear",
    "Gaming Devices",
    "Gift Cards",
    "Headphones",
    "Household Items",
    "IDs & Licenses",
    "Jewelry",
    "Keys",
    "Laptop",
    "Medical Devices",
    "Musical Instruments",
    "Office Supplies",
    "Pet Items",
    "Phone",
    "Sports Equipment",
    "Tablets",
    "Tools",
    "Toys",
    "Umbrella",
    "Wallet",
    "Watch",
    "Miscellaneous",
    // ... and so on, add any categories you need
  ];
  